plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  TargetRailsVersion: 6.1
  Exclude:
    - bin/bundle
    - db/queue_schema.rb
    - db/schema.rb
    - tmp/**/*
    - "**/*.gemspec"

Metrics/AbcSize:
  Exclude:
    - "**/helpers/**/*"

Metrics/BlockLength:
  Exclude:
    - "**/config/**/*"
    - "**/lib/tasks/**/*"
    - "**/spec/**/*"

Metrics/MethodLength:
  Exclude:
    - "**/helpers/**/*"

Metrics/ModuleLength:
  Exclude:
    - "**/helpers/**/*"

Naming/PredicateMethod:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
